
tasks:
  - name: Terminal
    init: make
    command: |
      printf "Waiting for Sock Store at $(gp url 3000) ..."
      gp await-port 80
      gp preview $(gp url 80) || true
      gp open deploy/docker-compose/docker-compose.yml

  - name: Docker Compose
    command: docker-compose -f deploy/docker-compose/docker-compose.yml up
    openMode: split-right

ports:
  - port: 80  # http
    onOpen: notify
  - port: 8080  # gitlab-docs
    onOpen: notify

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - ms-python.python
    - hashicorp.terraform
    - rebornix.ruby
    - yzhang.markdown-all-in-one